[package]
name = "dbgf"
version = "0.1.2"
edition = "2021"
authors = ["sarah <>"]
description = "dbg with a format string"
readme = "README.md"
repository = "https://github.com/sarah-ek/dbgf/"
license = "MIT"
keywords = ["debug", "format"]

[dependencies]
